# Generated by Django 5.0.1 on 2024-01-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pustak',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='book_covers/'),
        ),
    ]
