# Generated by Django 5.0.1 on 2024-01-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0003_remove_pustak_publication_date_pustak_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pustak',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='media/book_covers/'),
        ),
        migrations.AlterField(
            model_name='pustak',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/books/'),
        ),
    ]
