# Generated by Django 5.0.1 on 2024-01-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0004_alter_pustak_book_cover_alter_pustak_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pustak',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='pustak',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
